### ISSUE TITLE
can you update this project to work with ml-agents 0.10+?

### ISSUE THREAD

**Issue by BenDerPan** [mbaske/robot-ants#3]
this is a nice demo, but when I try to run it with ml-agents 0.11, there is no brain loaded.
![image](https://user-images.githubusercontent.com/10903567/69302146-a2b7e100-0c53-11ea-93da-7f5a67fe3311.png)

**Comment by mbaske** [comment]
Thanks @BenDerPan - I've now updated the project for ml-agents v0.11.

**Comment by BenDerPan** [comment]
Thanks :)
